name: Lint Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: self-hosted
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.10"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint models
        run: |
          sqlfluff lint --dialect snowflake --format github-annotation --annotation-level failure --nofail ${{ steps.get_files_to_lint.outputs.lintees }} > annotations.json


      - name: Annotate
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: "${{ secrets.TOKKEN }}"
          title: "Lint Models"
          input: "./annotations.json"
